[tool.poetry]
name = "ticktok"
version = "0.1.0"
description = ""
authors = ["elis"]

[tool.poetry.dependencies]
python = "^3.6"
pytest = "^6.1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
