name: Publish to PyPI

on:
  release:
    types: [published, edited]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: Gr1N/setup-poetry@v4
    - name: Build package
      run: poetry build
    - name: Publish to PyPI
      run: |
        poetry config pypi-token.pypi $PYPI_TOKEN
        poetry publish
